######################################################################
# Automatically generated by qmake (2.01a) niedz. cze 19 10:25:11 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += new_version.h
FORMS += plansza.ui
SOURCES += main.cpp new_version.cpp
