######################################################################
# Automatically generated by qmake (2.01a) niedz. cze 19 00:53:15 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += new_version.h
FORMS += plansza.ui
SOURCES += main.cpp
